<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ekskul_Model extends CI_Model
{

    public $table = 'tbl_ekskul';
    public $id = 'id_ekskul';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $session = $this->session->userdata('id_sekolah');

        if($session != 0){
            $this->datatables->select('id_ekskul,nama_ekskul,deskripsi,pembina,image,ketua,id_sekolah');
            $this->datatables->where('id_sekolah',$session);
            $this->datatables->from('tbl_ekskul');
            //add this line for join
            //$this->datatables->join('table2', 'tbl_ekskul.field = table2.field');
            $this->datatables->add_column('action', anchor(site_url('ekskul/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('ekskul/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                    ".anchor(site_url('ekskul/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_ekskul');
            return $this->datatables->generate();
        }else{
            $this->datatables->select('id_ekskul,nama_ekskul,deskripsi,pembina,image,ketua,id_sekolah');
         
            $this->datatables->from('tbl_ekskul');
            //add this line for join
            //$this->datatables->join('table2', 'tbl_ekskul.field = table2.field');
            $this->datatables->add_column('action', anchor(site_url('ekskul/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('ekskul/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                    ".anchor(site_url('ekskul/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_ekskul');
            return $this->datatables->generate();
        }
       
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ekskul', $q);
	$this->db->or_like('nama_ekskul', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('pembina', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('ketua', $q);
	$this->db->or_like('id_sekolah', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ekskul', $q);
	$this->db->or_like('nama_ekskul', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('pembina', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('ketua', $q);
	$this->db->or_like('id_sekolah', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
    function get_gambar($id){
        $this->db->where('id_ekskul',$id);
        return $this->db->get('tbl_ekskul')->result();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ekskul_Model.php */
/* Location: ./application/models/Ekskul_Model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-26 16:01:07 */
/* http://harviacode.com */