<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Profile_sekolah_model extends CI_Model
{

    public $table = 'tbl_profile_sekolah';
    public $id = 'id_sekolah';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_sekolah,nama_sekolah,alamat,email,no_telp,logo_sekolah,visi_misi,kalender_akademik');
        $this->datatables->from('tbl_profile_sekolah');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_profile_sekolah.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('profile_sekolah/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('profile_sekolah/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('profile_sekolah/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_sekolah');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sekolah', $q);
	$this->db->or_like('nama_sekolah', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('logo_sekolah', $q);
	$this->db->or_like('visi_misi', $q);
	$this->db->or_like('kalender_akademik', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sekolah', $q);
	$this->db->or_like('nama_sekolah', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('logo_sekolah', $q);
	$this->db->or_like('visi_misi', $q);
	$this->db->or_like('kalender_akademik', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Profile_sekolah_model.php */
/* Location: ./application/models/Profile_sekolah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-05 18:57:12 */
/* http://harviacode.com */